name: Build and Push Docker Image
description: Build and push a Docker image to a container registry

inputs:
  root-dir:
    required: true
    description: The root dir of Dockerfile
  image-name:
    required: true
    description: Name of the image to build
  mage-tag:
    required: true
    description: Tag created for the image
  release-branch:
    required: false
    description: Name of current release branch
  dockerhub-username:
    required: true
    description: Dockerhub username
  dockerhub-password:
    required: true
    description: Dockerhub password

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: inputs.push == 'true'
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: ${{ inputs.root-dir }}/Dockerfile
        push: ${{ inputs.push }}
        directory: ${{ inputs.root-dir }}
        registry: registry.infra.basetensors.com
        tags: |
          test/${{ inputs.image-name }}:${{ inputs.image-tag }}
        cache-from: type=gha,mode=max,ref=master
        cache-to: type=gha,mode=max,ref=master
      env:
        DOCKER_BUILDKIT: "1"